typography_spectrum: 0.561625937698409
color:
  brandColors:
    - '#292929'
    - '#5B7876'
    - '#8F9E8B'
    - '#F2E6B6'
    - '#412A22'
  brandStrength: 0.26137744798325
  lightness: 0.7048581002745777
  saturation: 0.5037592698354274
  rhythmicContrast: 0.8724476359784603
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6760968894232064
analytics:
  google: null
  facebook: null
  twitter: null
name: Michael Swamer Photo
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'About '
    id: 8b1f5082-3542-4692-a504-14e32c9d916f
    type: content
  - name: Formative Years
    id: fa5e6f31-983d-43c7-b5a1-e60d06549256
    type: content
favicon: null
title: Contact Sheet
purpose: []
