layout_spectrum: 0.6760968894232064
typography_spectrum: 0.8849246427416801
color:
  brandColors:
    - '#292929'
    - '#5B7876'
    - '#8F9E8B'
    - '#F2E6B6'
    - '#412A22'
  brandStrength: 0.26137744798325
  lightness: 0.7048581002745777
  saturation: 0.5037592698354274
  rhythmicContrast: 0.8724476359784603
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Michael Swamer Photo
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Contact Sheet
purpose: []
